Minimize tweaks
green-coding-berlin/eco-ci-energy-estimation pull request #53
Opened 2023-11-30 13:55 UTC by dan-mm

Cleaner looking output. 

Now also checks comments for both the user (github bot) + Eco-CI as a string within the message

2023-12-01 10:29 UTC, ArneTR requested changes

2023-12-01 10:29 UTC, ArneTR commented on scripts/setup.sh
> +    source "$(dirname "$0")/vars.sh" add_var API_BASE "https://b67e-62-214-9-98.ngrok-free.app"
why is there still a grok command in there?

2023-12-01 12:25 UTC, dan-mm commented on scripts/setup.sh
> +    source "$(dirname "$0")/vars.sh" add_var API_BASE "https://b67e-62-214-9-98.ngrok-free.app"
I was showcasing something during the workshop, this snuck in. thanks for the catch, its gone now

2023-12-02 07:29 UTC, ArneTR commented
Can you clarify why there is a hardcoded API_BASE variable in the code?

The way I understand the add_var function it will update this variable. So will a user not always left with this API_BASE configured then? I thought.

The variable should be able to be set by the surrounding github actions workflow file, right? So if you can set it there, why is there a hardcoding option that you temporarily patched in the first place?

2023-12-12 14:44 UTC, merged